# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonImplementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PythonRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('python_version', models.CharField(max_length=20)),
                ('release_date', models.DateField(verbose_name='date released')),
                ('kind', models.CharField(choices=[('full', 'Full release'), ('source', 'Source-only release')], default='full', max_length=10)),
                ('implementation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='release_latency.PythonImplementation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pythonrelease',
            unique_together=set([('implementation', 'version')]),
        ),
    ]
